### PR TITLE
Python 3 Fixes

### PR DESCRIPTION
**Pull request by ChrisPattison**
As is currently, there are a few parts of PyCFTBoot that do not run under Python 3. 

The usual issue is attempting to index into dict.keys() which returns a view in Python 3

This changeset should be Python 2.7 compatible according to the docs, but I am unable to test

### CODE REVIEW

**Comment by ChrisPattison** [comment]
I am still ironing out some subtle bugs with a few of the examples, but opened up the PR to get this on the radar

**Comment by spraharsh** [comment]
you might also want to check using [futurize](https://python-future.org/futurize.html). it automates the switch to 3 while keeping the library python 2 compatible. but it's been a while since I've looked at PyCFTBoot though

**Comment by cbehan** [comment]
Thanks! I'm uneasy about the idea to use pip but the other two commits are now in the repo.

**Comment by ChrisPattison** [comment]
> Thanks! I'm uneasy about the idea to use pip but the other two commits are now in the repo.

Great! Regarding not using pip, do you have a particular reason for this viewpoint?

**Comment by cbehan** [comment]
Pip doesn't know about sdpb and unisolve so the list of dependencies would have to be incomplete. This is also not purely a library. So I think distributions wanting to package this might want to set custom paths for utilities like /usr/bin/pycfboot-tutorial.py and /usr/bin/pycftboot-wrap.py. I know some people use pip as a backup for situations when their distro package manager is too cumbersome. But otherwise I'm quite unfamiliar with it, especially when it comes to fixing bugs that might be filed in the future.

**Pull request closed without merging**
